const url = 'https://be-pj-desarrolloweb.herokuapp.com'
let user_list = 'https://be-pj-desarrolloweb.herokuapp.com/users/'
let curso_list = 'https://be-pj-desarrolloweb.herokuapp.com/curso/'
let carrera_list = 'https://be-pj-desarrolloweb.herokuapp.com/carrera/'
let homework_list = 'https://be-pj-desarrolloweb.herokuapp.com/homeworks'